name:                chatux-example-backend
version:             0.1.0.0
github:              "aiya000/chatux-example-backend"
license:             BSD3
author:              "aiya000"
maintainer:          "aiya000.develop@gmail.com"
copyright:           "aiya000"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Simple

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aiya000/chatux-example-backend#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chatux-example-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatux-example-backend

tests:
  chatux-example-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chatux-example-backend
