name: chatux-example-backend
version: 0.1.0.0
github: "aiya000/chatux-example-backend"
license: MIT
author: "aiya000"
maintainer: "aiya000.develop@gmail.com"
copyright:           "aiya000"
description: Please see the README on GitHub at https://github.com/aiya000/chatux-example-backend#README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fprint-explicit-kinds
  - -fprint-potential-instances

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - deriving-aeson
  - here
  - network
  - rio
  - safe-exceptions
  - servant-options
  - servant-server
  - tonatona
  - tonatona-logger
  - wai-cors
  - warp

library:
  source-dirs: src

executables:
  chatux-example-backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chatux-example-backend
